#Tue Aug 27 04:13:14 UTC 2024
micronaut:
  application:
    name: hostels

jpa:
  default:
    entity-scan:
      packages:
        - com.hostels.beans


datasources:
  default:
    url: jdbc:mysql://capsule.cxrdfvklio6j.us-east-1.rds.amazonaws.com:3306/capsule
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "admin"
    password: "admin123#"
    maximum-pool-size: 10
    allow-pool-suspension: true
    dialect: MYSQL